version: "3.9"

services:
  database_foodconnection: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_foodconnection
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foodconnection
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: foodconnection
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
    network_mode: host

volumes:
  pgdata:
    driver: local