name: CI

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Install Dependencias
        run: yarn
        
      - name: build
        run: yarn build
      
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "~/app/foodConnection"
      
      
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app/foodConnection
            yarn
            ./node_modules/.bin/prisma migrate dev
            pm2 restart foodConnectionApi

