name: CI

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubundu-22.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Install Dependencias
        run: yarn
        
      - name: build
        run: yarn build
      
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_ }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "test"
        
